BigJobCpu: 24
BigJobMem: 64000
BigJobTimeMin: 1440
COMPRESSION: 1
CONTIG_MINLENGTH: 1000
CUTTAIL_WINDOW: 25
DEDUP_ACCURACY: 4
Databases: null
ENTROPY: 0.5
ENTROPYWINDOW: 25
Host: human
MediumJobCpu: 16
MediumJobMem: 32000
MoreRamCpu: 2
MoreRamMem: 16000
Output: S_SE.out
Preprocess: paired
QSCORE: 15
READ_MINLENGTH: 90
Reads: S_SE
Search: sensitive
SmallJobCpu: 8
SmallJobMem: 16000
canuSettings: correctedErrorRate=0.16 maxInputCoverage=10000 minInputCoverage=0 corOutCoverage=10000
  corMhapSensitivity=high corMinCoverage=0 useGrid=False stopOnLowCoverage=False genomeSize=10M
  -nanopore
filtAAprimary: --min-length 30 -e 1e-3
filtAAsecondary: --min-length 30 -e 1e-5
filtNTprimary: --min-length 90 -e 1e-10
filtNTsecondary: --min-length 90 -e 1e-20
linclustParams: --kmer-per-seq-scale 0.3 -c 0.8 --cov-mode 1 --min-seq-id 0.97 --alignment-mode
  3
perfAA: --start-sens 1 --sens-steps 3 -s 7 --lca-mode 2 --shuffle 0
perfAAfast: -s 4.0 --lca-mode 2 --shuffle 0
perfNT: --start-sens 2 -s 7 --sens-steps 3
perfNTfast: -s 4.0
taxIdIgnore: 0 1 2 10239 131567 12429 2759
